### ISSUE TITLE
Add location for errors on validation

### ISSUE THREAD

**Issue by pjmolina** [Mermade/swagger2openapi#1]
Feature request: I would be very nice to provide context info to help locate the errors reported on validation. 

- Line/col can work. 
- A ref to the point like: /components/schemas/a would be great. 
- Both would excels!

**Comment by MikeRalphson** [comment]
@pjmolina  I was thinking along similar lines earlier, and also that it would be nice to collect all errors rather than halting at the first.

A couple of things make this slightly complex:

* I process the OpenAPI definition as a Javascript object, so no direct access to line/col position in the source json/yaml file
* Error messages are created by the [should.js](https://github.com/shouldjs/should.js/) testing framework, which provides a way to override messages, but not to append context (as far as I am aware)
* `should.js` throws an Exception when an assertion tests false and the validation stops

When the OpenAPI Initiative publish a v3.0.x schema, we will have the option of validating with something like [ajv](https://github.com/epoberezkin/ajv), which usually gives some useful context.

I think trying to give a rough JSON-Pointer style context should be achievable. Let me investigate with a broken v3 file I have here.

**Comment by MikeRalphson** [comment]
@pjmolina It's not complete as far as reporting every containing object, but the validator will now respond with a `context` property containing a JSON-Pointer string, e.g.:

````json
#/paths/~1pet~1findByStatus/get/parameters/0
````

And thank-you again for prodding me to add the feature.

**Comment by pjmolina** [comment]
Excellent +1. You are fast!

**Comment by MikeRalphson** [comment]
Please re-open if you spot any issues where the given context is not accurate (enough).
