### ISSUE TITLE
Spec conversion support in the browser

### ISSUE THREAD

**Issue by spilio** [Mermade/swagger2openapi#16]
Hi @MikeRalphson!  Are there any plans for bundling a JS library for converting specs directly within the browser environment?

**Comment by MikeRalphson** [comment]
Hi! There is rudimentary support for webpack to create a browser bundle, and api-spec-converter successfully uses swagger2openapi with browserify. 

The resultant bundles are really large though because of dependencies, so I'm not totally happy with them as a solution. There is also a PR to update webpack to the latest version which might help with the size issue.

Any help from people with more browser-side experience would be gratefully received!

One other option is to call the web-based converter API using AJAX, I do this in openapi-gui.

**Comment by spilio** [comment]
Hey Mike thanks for the quick response mate!  I think for now I'll stick with the API version of your tool.  Thanks a lot.
